"""initial_schema

Revision ID: 9ff561eeeca5
Revises: 
Create Date: 2026-05-20 14:38:49.793200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff561eeeca5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_filaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('material', sa.String(length=50), nullable=False),
    sa.Column('color_name', sa.String(length=100), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('diameter', sa.Float(), nullable=False),
    sa.Column('source_url_template', sa.String(length=1000), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_filaments_brand'), 'community_filaments', ['brand'], unique=False)
    op.create_index('ix_community_filaments_brand_material', 'community_filaments', ['brand', 'material'], unique=False)
    op.create_index(op.f('ix_community_filaments_id'), 'community_filaments', ['id'], unique=False)
    op.create_index(op.f('ix_community_filaments_material'), 'community_filaments', ['material'], unique=False)
    op.create_table('import_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('designer', sa.String(length=200), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_cache_id'), 'import_cache', ['id'], unique=False)
    op.create_index(op.f('ix_import_cache_source_url'), 'import_cache', ['source_url'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_users_stripe_subscription_id'), 'users', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('filaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('material', sa.String(length=50), nullable=False),
    sa.Column('color_name', sa.String(length=100), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('diameter', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('price_at_save', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filaments_id'), 'filaments', ['id'], unique=False)
    op.create_index(op.f('ix_filaments_user_id'), 'filaments', ['user_id'], unique=False)
    op.create_table('printers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printers_id'), 'printers', ['id'], unique=False)
    op.create_index(op.f('ix_printers_user_id'), 'printers', ['user_id'], unique=False)
    op.create_table('prints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('designer', sa.String(length=200), nullable=True),
    sa.Column('source_platform', sa.String(length=30), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.Column('filament_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('queued', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('print_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prints_id'), 'prints', ['id'], unique=False)
    op.create_index(op.f('ix_prints_is_public'), 'prints', ['is_public'], unique=False)
    op.create_index(op.f('ix_prints_printer_id'), 'prints', ['printer_id'], unique=False)
    op.create_index(op.f('ix_prints_queued'), 'prints', ['queued'], unique=False)
    op.create_index('ix_prints_user_created', 'prints', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_prints_user_id'), 'prints', ['user_id'], unique=False)
    op.create_index('ix_prints_user_queued', 'prints', ['user_id', 'queued'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prints_user_queued', table_name='prints')
    op.drop_index(op.f('ix_prints_user_id'), table_name='prints')
    op.drop_index('ix_prints_user_created', table_name='prints')
    op.drop_index(op.f('ix_prints_queued'), table_name='prints')
    op.drop_index(op.f('ix_prints_printer_id'), table_name='prints')
    op.drop_index(op.f('ix_prints_is_public'), table_name='prints')
    op.drop_index(op.f('ix_prints_id'), table_name='prints')
    op.drop_table('prints')
    op.drop_index(op.f('ix_printers_user_id'), table_name='printers')
    op.drop_index(op.f('ix_printers_id'), table_name='printers')
    op.drop_table('printers')
    op.drop_index(op.f('ix_filaments_user_id'), table_name='filaments')
    op.drop_index(op.f('ix_filaments_id'), table_name='filaments')
    op.drop_table('filaments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_subscription_id'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_import_cache_source_url'), table_name='import_cache')
    op.drop_index(op.f('ix_import_cache_id'), table_name='import_cache')
    op.drop_table('import_cache')
    op.drop_index(op.f('ix_community_filaments_material'), table_name='community_filaments')
    op.drop_index(op.f('ix_community_filaments_id'), table_name='community_filaments')
    op.drop_index('ix_community_filaments_brand_material', table_name='community_filaments')
    op.drop_index(op.f('ix_community_filaments_brand'), table_name='community_filaments')
    op.drop_table('community_filaments')
    # ### end Alembic commands ###
